version: '2'
services:
  seleniumhub:
    image: selenium/hub
    ports:
      - 4444:4444
    networks:
        - forworkshop_default



  firefoxnode:
    image: selenium/node-firefox-debug
    ports:
      - 5900
    environment:
        - HUB_PORT_4444_TCP_ADDR=seleniumhub
        - HUB_PORT_4444_TCP_PORT=4444
    networks:
        - forworkshop_default



  chromenode:
    image: selenium/node-chrome-debug
    ports:
      - 5900
    environment:
        - HUB_PORT_4444_TCP_ADDR=seleniumhub
        - HUB_PORT_4444_TCP_PORT=4444
    networks:
        - forworkshop_default


  firefox3node:
    image: selenium/node-firefox-debug:3.4.0-bismuth
    ports:
      - 5900
    environment:
        - HUB_PORT_4444_TCP_ADDR=seleniumhub
        - HUB_PORT_4444_TCP_PORT=4444
    networks:
        - forworkshop_default


  headless:
    image: selenium/node-phantomjs
    environment:
        - HUB_PORT_4444_TCP_ADDR=seleniumhub
        - HUB_PORT_4444_TCP_PORT=4444
    networks:
        - forworkshop_default


  webdrivertests:
    image: vodqauserapp
    networks:
        - forworkshop_default


    volumes:
      - ./temp:/usr/src/app/target
    links:
      - "seleniumhub"
    command: bash -c "cd /usr/src/app && mvn test"

networks:
  forworkshop_default:
    external: true